version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A backend.celery_tasks worker --loglevel=INFO
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  flower:
    image: mher/flower
    env_file:
      - .env
    ports:
      - "5555:5555"

  fast_api:
    build: .
    command: uvicorn endpoint:app --host 0.0.0.0
    container_name: backend_app
    env_file: .env
    image: sephora-parser/users.py
    depends_on:
      - postgres
      - celery
    ports:
      - "8000:8000"
    volumes:
      - .:/code
